server:
  port: 8002
spring:
  application:
    name: Server-Consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
feign:
  hystrix:
    enabled: true