spring:
  application:
    name: Zuul-Gateway
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      url: http://localhost:8001
    api-b:
      path: /api-b/**
      serviceId: server-provider
    api-c:
      path: /api-c/**
      serviceId: server-consumer

